<?php

// $Id$


/**
 * @file
 * Configuration module for islandora_solr_search.module
 */

/**
 * Implementation of hook_alter_form.
 * Adds this module's configuration options to islandora_solr_search's configuration page.
 */
function cyct_solr_config_form_islandora_solr_admin_settings_alter(&$form, &$form_state) {
  $module = 'cyct_solr_config';
  $file = 'cyctResults.inc';
  $class = 'cyctSolrResults';
  $method = 'displayResults';
  $config_options = $form['islandora_solr_config_options']['#options'];
  $config_options["${module}~${file}~${class}~${method}"] = 'CYCT';
  $form['islandora_solr_config_options']['#options'] = $config_options;
}

/**
 * Implementation of hook_help()
 */
function cyct_solr_config_help($path, $arg) {

  switch ($path) {
    case 'admin/help#cyct_solr_config':
      return t("When 'Island Voices' is selected from the configuration dropdown in the<br />
        !page the following settings will be used.
        <ul>
        <li>Module - cyct_solr_config</l1>
        <li>File - cyctResults.inc</l1>
        <li>Class - cyctSolrResults</l1>
        <li>Method - displayResults</l1>
        </ul>
        ", array('!page' => l("Islandora Solr Search configuration page", 'admin/settings/islandora_solr_search'),)
      );
  }
}


